# Generated by Django 3.1.7 on 2021-03-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploader',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
