# Generated by Django 3.1.7 on 2021-03-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcodes', '0002_fileuploader_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='postcode',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
