# Generated by Django 3.1.7 on 2021-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcodes', '0004_auto_20210316_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='code',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
